added first and second steps
MilkyBay/react-burger pull request #1
Opened 2022-05-04 15:14 UTC by MilkyBay

2022-05-04 16:21 UTC, andryxxa93 requested changes
Работа проделана огромная! Вы отлично потрудились. Хорошо типизированы все компоненты. Повторяющаяся верстка вынесена в отдельные компоненты. Модальное окно закрывает по клавише Escape. Так держать!

Правда есть пару моментов, которые необходимо исправить, чтобы работа была принята:
1) Добавьте ингредиенты в конструктор, чтобы можно было проверить соответствие макету.
2) Добавьте проверку ответа сервера - res.ok:

Чтобы код стал чище и понятнее, можно улучшить ещё несколько моментов (не обязательно) : 
1) Согласно макету если ингредиент не добавлен в конструктор, то счетчик не отображается. 
2) Лучше не писать каждый раз props, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз.
3) Не использовать index для атрибута key.
4) Упростить условные конструкции. 
5) Добавить атрибут key там где его нет.
6) Вызов к api можно вынести в отдельный файл в директорию utils.

В pull request вы найдете комментарии с более подробным описанием проблемы.

Удачных правок!

2022-05-04 16:21 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  }, []);
Необходимо исправить:
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-05-04 16:21 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +const BurgerConstructor = (props) => {
Можно лучше:
Здесь и в коде других компонентов, лучше не писать каждый раз props, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-05-04 16:21 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +                key={index}
Можно лучше:
Это хорошо, что используется атрибут key, но записывать в него index плохая практика, почему описано вот тут - https://ru.react.js.org/docs/lists-and-keys.html#%D0%9A%D0%BB%D1%8E%D1%87%D0%B8.
У каждого ингредиента есть свойство _id, можно использовать его.

2022-05-04 16:21 UTC, andryxxa93 commented on src/components/burger-constructor/constructor-item/constructor-item.jsx
> +  const type = index === 0 ? "top" : index === arrayLength - 1 ? "bottom" : "";
Можно лучше:
Очень сложная конструкция получилась - надо или упростить или поменять логику.

2022-05-04 16:21 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredient-details/ingredient-details.jsx
> +        ))}
Можно лучше:
У каждого элемента массива должен быть ключ (key). Ключ - это специальный строковый атрибут, который нужно указывать при создании списка элементов.

Ключи помогают реакту определять, какие элементы были изменены, добавлены или удалены. Их необходимо указывать, чтобы реакт мог сопоставлять элементы массива с течением времени.

(https://ru.reactjs.org/docs/lists-and-keys.html#gatsby-focus-wrapper)

2022-05-04 16:21 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
> +      <Counter size="default" count={0} />
Можно лучше: можно добавить условный рендеринг и не показывать счетчик если элемент не добавлен в конструктор

2022-05-04 18:47 UTC, MilkyBay commented on src/components/burger-constructor/burger-constructor.jsx
> +                key={index}
мы можем добавлять одни и те же ингредиенты по несколько раз, следовательно _id этих ингредиентов может повторяться (решил проблему склеиванием id и index в строку)
конкретно в этом месте это актуально, но в других местах, где используется index, порядок не будет нарушен (например удалением элементов при map)

2022-05-05 19:23 UTC, andryxxa93 approved these changes
Отлично! Все замечания исправлены. Ваша работа принята!

В pull request есть пару не критических замечаний, их исправлять не обязательно, но они позволят сделать код чуточку лучше.

Желаю удачного продолжения обучения!

2022-05-05 19:23 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        .then((data) => Promise.resolve(filterData(data.data)))
Можно улучшить: необходимости в Promise.resolve здесь нет.

2022-05-05 19:23 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredient-details/ingredient-details.jsx
> +  element: { name, image_large, calories, proteins, fat, carbohydrates },
Отлично, использована сложная деструктуризация!

2022-05-05 19:23 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
> +      {count > 0 && <Counter size="default" count={count} />}
Можно улучшить:
Оператор AND приводит к булиновому значению оба операнда. Ноль всегда будет равен - false. Поэтому можно упростить - `{count && <Counter size="default" count={count} />}`

2022-05-05 22:40 UTC, merged